### ISSUE TITLE
Improve braket

### ISSUE THREAD

**Issue by peng1999** [Leedehai/typst-physics#1]
Current implementation gives inconsistent height of angles and vertical bars in `braket`. Until typst/typst#641 have merged, I propose to use following workaround to make the formula more pleasant.

```typst
#let braket(bra, ket) = style(styles => {
  let height = measure($ bra ket $, styles).height;
  let phantom = box(height: height, width: 0pt, inset: 0pt, stroke: none);
  $ lr(angle.l bra lr(|phantom#h(0pt)) ket angle.r) $
})
```

Result:
![image](https://user-images.githubusercontent.com/12483662/233521107-e3a684e6-936d-4c64-a65e-485593cfc38a.png)

**Comment by Leedehai** [comment]
谢啦
