### ISSUE TITLE
Hessian Matrix formula is wrong

### ISSUE THREAD

**Issue by dedekindcut** [Leedehai/typst-physics#12]
From the manual:

<img width="773" alt="Screenshot 2023-10-24 at 10 07 27 PM" src="https://github.com/Leedehai/typst-physics/assets/13700355/c2afd582-2d08-49b6-bedc-bddcec5cd552">

The Hessian is the matrix of second order partial derivatives, so for 3x3 matrices and higher the matrix should still consist of $\dfrac{\partial^2}{\partial x_i \partial x_j}$. Currently for 3x3 `hmat` generates a matrix with elements such as $\dfrac{\partial^3}{\partial x \partial z}$, which is incorrect. The superscript in the numerator should always be 2 no matter the dimension.

From the [wikipedia page](https://en.wikipedia.org/wiki/Hessian_matrix):

<img width="701" alt="Screenshot 2023-10-24 at 10 11 46 PM" src="https://github.com/Leedehai/typst-physics/assets/13700355/32c0439d-ae73-48a6-8716-45368f0553da">

Thanks for all your hard work on this package! It's now a must have for me when using Typst.

**Comment by Leedehai** [comment]
Fixed by that PR https://github.com/Leedehai/typst-physics/pull/13. Thanks!

**Comment by Leedehai** [comment]
Fixed by that PR https://github.com/Leedehai/typst-physics/pull/13. Thanks!
