### ISSUE TITLE
mel needs beautify

### ISSUE THREAD

**Issue by zrt2002** [Leedehai/typst-physics#16]
This code snippet
`$ mel(phi_n^0, sqrt((2 hbar) / (m omega))(a^dagger + a), phi_n^0) $`
gives 
![image](https://github.com/Leedehai/typst-physics/assets/55143732/574b69a9-2c1e-4224-b1eb-84af2c69484b)
in which the vertical bar is too bold and slightly higher than my braket. Besides, the space between alphabet and bar is too tight.

**Comment by Leedehai** [comment]
Thanks. Admittedly this has been a longstanding pain issue and I do not have an answer.

Boldness and tightness: sorry, this is rooted in Typst's layout strategy and could not be solved cleanly at the package level.

Height of vertical bar: the package uses a hack to calculate the height, and it is not reliable as you saw from the example. There's an issue created at Typst (https://github.com/typst/typst/issues/240), and I very much look forward to a native solution to get rid of the hack.

**Comment by Leedehai** [comment]
Update: I have a draft to make the Typst compiler handle this natively: https://github.com/Leedehai/typst/pull/1/files

**Comment by Leedehai** [comment]
Upgraded `physica` to v0.9.0. It requires Typst compiler 0.10.0, which has my PRs https://github.com/typst/typst/pull/2760 and https://github.com/typst/typst/pull/2764 to fix this issue.

After https://github.com/typst/packages/pull/277 is merged as well, `physica` v0.9.0 will be auto-downloadable by the compiler and the typst.app web app.
