### ISSUE TITLE
Wrong upright style and spacing for vecrow() and Greek letters

### ISSUE THREAD

**Issue by CarrotDLaw** [Leedehai/typst-physics#19]
When the first element in `vecrow()` is a Greek letter, there are unexpected spacing and upright style issues, like the first three lines in the following. The last three lines are how the output is supposed to be.

I found a temporary solution that is to use `italic(alpha)` instead of just `alpha` in the first element, though.

```
$
& vecrow(alpha, beta) \
& vecrow(alpha, italic(beta)) \
& vecrow(alpha, b) \
& vecrow(a, beta) \
& vecrow(italic(alpha), beta) \
& (alpha, beta) \
$
```

<img width="246" alt="image" src="https://github.com/Leedehai/typst-physics/assets/52628857/bb3a3a04-e7ff-473b-a819-88a9db2d77c3">

**Comment by YDX-2147483647** [comment]
Some investigation:

https://github.com/Leedehai/typst-physics/blob/94c89824cbb69d1513e49ea7ea3d0bd90f7016fd/physica.typ#L152

![test](https://github.com/Leedehai/typst-physics/assets/73375426/82a9a352-777e-4a7f-b20c-d9ff592ade5d)

```typst
#grid(columns: (1fr, 1fr), [
  ```typst $lr((alpha, beta/gamma))$```

  $lr((alpha, beta/gamma))$

  #repr($lr((alpha, beta/gamma))$)
], [
  ```typst $vecrow(alpha, beta/gamma)$```

  $vecrow(alpha, beta/gamma)$

  #repr($vecrow(alpha, beta/gamma)$)
])
```

**Comment by Leedehai** [comment]
Wow, thanks! Let me see..

**Comment by Leedehai** [comment]
It works 👍 I committed 8df2cc42fbdd7a3abf3abbaa9035eb17c9b0f838 and add you as the author.
