### ISSUE TITLE
Unexpected output of iprod()

### ISSUE THREAD

**Issue by CarrotDLaw** [Leedehai/typst-physics#20]
As per the latest manual of physica, the behaviour of `iprod()` should be the one shown in the first line. However, the actual output is the one in the second line. 

```
$
& angle.l u, v angle.r \
& iprod(u, v) \
& braket(u, v)
$
```

<img width="266" alt="image" src="https://github.com/Leedehai/typst-physics/assets/52628857/3cd1960f-766b-455b-a368-d75e2a00c86c">

**Comment by YDX-2147483647** [comment]
> As per the latest manual of physica, the behaviour of `iprod()` should be the one shown in the first line.

Could you specify which is _the latest manual of physica_? I have checked [v0.7.5](https://github.com/Leedehai/typst-physics/releases/tag/v0.7.5) to [v0.9.0](https://github.com/Leedehai/typst-physics/releases/tag/v0.9.0)…

![](https://github.com/Leedehai/typst-physics/assets/73375426/15bf567b-4b80-4d88-8978-74b493087450)

**Comment by CarrotDLaw** [comment]
I apologise that I have read the manual wrong! I will now close this issue.

**Comment by CarrotDLaw** [comment]
The manual of 0.9.0 is as follows.

<img width="481" alt="image" src="https://github.com/Leedehai/typst-physics/assets/52628857/fc502b3b-b70d-4193-94dc-f5edb10a1876">

**Comment by YDX-2147483647** [comment]
Well, I downloaded the manual from https://github.com/Leedehai/typst-physics/releases, and I guess you downloaded it from the repo…

**Comment by CarrotDLaw** [comment]
I did, indeed. So I will really close this issue.

**Comment by Leedehai** [comment]
Yeah thanks for pointing it out.. I'm working on some changes and release as 0.9.1. That iprod() change is part of that future release.

**Comment by Leedehai** [comment]
Update: I updated to 0.9.1 and made a PR to upload it to the official package repo: https://github.com/typst/packages/pull/304

After that PR is merged, the package will be available for Typst's auto-loading and the web app.

Thanks again for catching this :)
