### ISSUE TITLE
Add option for derivative at a certain point

### ISSUE THREAD

**Issue by tobiasdiez** [Leedehai/typst-physics#28]
One sometimes needs to specify the point / time at which one takes the derivative, using a vertical bar.

In typst, this can be approximated using
```
dv(,t)| _(t=0) f(t)
```
which kind of works but looks ugly since the bar is too short. It would be nice if one could use something like `dv(,t, t=0)` or `dv(,t, at=(t=0))` which automatically yields a proper rending of the bar.

Looking at the code, typst seems to use the method [stretch_vertical](https://github.com/search?q=repo%3Atypst%2Ftypst%20stretch_vertical&type=code) to increase the length of lines/bars.

**Comment by YDX-2147483647** [comment]
Here's a workaround.

```typst
#import "@preview/physica:0.9.3": dv, eval
$ eval(dv(,t))_(t=0) f(t) $
```

![](https://github.com/Leedehai/typst-physics/assets/73375426/337de4ea-b04c-459b-be56-b629315ff455)

**Comment by Leedehai** [comment]
Thanks, the above snippet is not merely a workaround, it's actually the intended usage.

I feel it's better not to couple different semantics together, but I welcome more inputs in this to convince me - no promise:)

**Comment by YDX-2147483647** [comment]
[Typst v0.8.0 changelog](https://typst.app/docs/changelog/#v0.8.0):
> Removed support for automatic matching of fences like `|` and `||` as there were too many false positives. You can use functions like [abs](https://typst.app/docs/reference/math/lr/#functions-abs) or [norm](https://typst.app/docs/reference/math/lr/#functions-norm) or an explicit [lr](https://typst.app/docs/reference/math/lr/#functions-lr) call instead. (**Breaking change**)

Therefore I guess the activate character is impossible without changing the typst compiler.

---

Besides, I've updated https://github.com/Leedehai/typst-physics/issues/28#issuecomment-2087891080 with 2 example functions. Hope they satisfy your need.

**Comment by tobiasdiez** [comment]
Thanks!

As another data point, the https://typst.app/universe/package/diverential package has an `eval` argument for derivatives and the example reads quite nice
```
dv(f, x, deg: 2, eval: 0)
```
But I will not argue further if you think the eval method is already sufficient 🦊
