### ISSUE TITLE
More attractive README needed

### ISSUE THREAD

**Issue by YDX-2147483647** [Leedehai/typst-physics#3]
This is a great package! But people may miss it if they don't dive into the demo (`physics-manual.pdf`)…

How about add a screenshot to README?

## Additional information

[Typst](https://typst.app/docs/tutorial/writing-in-typst/), [KaTeX](https://katex.org/), [MathJax](https://mathjax.org/) and all of them have screenshots.

![typst](https://user-images.githubusercontent.com/73375426/235851271-7e597b2d-4cc9-46fd-9251-e1b657f93fb3.png)
![katex](https://user-images.githubusercontent.com/73375426/235851794-e3106e34-ba83-497f-b1a4-fc81a53be454.png)
![mathjax](https://user-images.githubusercontent.com/73375426/235851858-fed681cf-c390-4989-98e1-4549646dc75e.png)

**Comment by Leedehai** [comment]
Thanks for the suggestion. Let me paste this to README.md, using GitHub as an image bed:
<img width="832" alt="Screenshot 2023-05-03 at 19 36 50" src="https://user-images.githubusercontent.com/18319900/236073825-e91b4601-7e92-490b-a7e4-e9e405a2147b.png">
