### ISSUE TITLE
Add shortcuts for plus.minus and minus.plus

### ISSUE THREAD

**Issue by adamanteye** [Leedehai/typst-physics#30]
`let pm = $plus.minus$` saved me a lot of time, I wonder if it is okay to make this as a default option.

**Comment by YDX-2147483647** [comment]
FYI, [quick-maths – Typst Universe](https://typst.app/universe/package/quick-maths) allows us to write `+-`.

```typst
#import "@preview/quick-maths:0.1.0": shorthands

#show: shorthands.with(
  ($+-$, $plus.minus$),
  ($|-$, math.tack),
  ($<=$, math.arrow.l.double) // Replaces '≤'
)

$ x^2 = 9 quad <==> quad x = +-3 $
```

**Comment by adamanteye** [comment]
Wow, this is what I need, thank you!
