### ISSUE TITLE
Request: Physical constants

### ISSUE THREAD

**Issue by marisbaier** [Leedehai/typst-physics#31]
Excuse me not knowing if this is the right place to ask but wouldn't physical constants be an amazing addition to this package?

**Comment by Leedehai** [comment]
What constants you have in mind? I feel most of the time it's more convenient & clearer to just type the constants with native Typst..

**Comment by marisbaier** [comment]
Hi, I meant something like
`#let m_e = 9.1093837*calc.pow(10,-31)`
...

Just because I came into the habit of doing quick calculations directly in typst for my homework assignments. Currently I have them in a seperate file and I use them `hbar^2 approx #(const.hbar^2)`
