### ISSUE TITLE
Request:  Symbol of Assigning Differental Equation

### ISSUE THREAD

**Issue by naoppy** [Leedehai/typst-physics#33]
![image](https://github.com/user-attachments/assets/8bc4a1a2-7776-431f-a512-678479c6cf99)

I am not sure if this notation is common in the world, but how about supporting the notation of assigning values to differentiated functions in physica?

below code shows above image with normal typst.
```
$
  lr((dif) / (dif t) L(x(t))|)_(t=0)
$
```

or with physica, 
```
$
  lr(dv(, t)L(x(t))|)_(t=0)
$
```

Since this needs `lr` and is difficult for the public to understand, how about giving some support with physica?

**Comment by YDX-2147483647** [comment]
Maybe #28 would help?

**Comment by naoppy** [comment]
Oh I had missed `eval` function. Thank you for telling.
