### ISSUE TITLE
add commutator

### ISSUE THREAD

**Issue by oameye** [Leedehai/typst-physics#37]
Could we add the commutator and anticommutator just as in the latex physics package?

**Comment by YDX-2147483647** [comment]
Maybe literal `[] {}` are enough?

```typst
$ [tilde(A), {tilde(B), tilde(C)}] + [f(x), {x, y}]. $
```

![无标题](https://github.com/user-attachments/assets/0834252b-dd68-4200-9b25-426bfff8fbc7)

**Comment by Leedehai** [comment]
Hi I considered that but concluded `[]` and `{}` are enough. Typst is able to automatically adjust the height of the delimiters based on the content within, but LaTeX can't do that (i.e. you have to manually add `\left`, `\right`) and I guess that's why the `physics` package for LaTeX has them.

**Comment by oameye** [comment]
I didn't know this, thanks a lot :)
