### ISSUE TITLE
`hbar` is affected by `#show strike: …`

### ISSUE THREAD

**Issue by YDX-2147483647** [Leedehai/typst-physics#38]
`hbar` is affected by `#show strike: …` unexpectedly.

```typst
#import "@preview/physica:0.9.3": hbar
#show strike: set text(gray)
$hbar planck.reduce$
```
![](https://github.com/user-attachments/assets/4337d278-9ce4-42ae-81c1-d58b8f055323)

Because the solution in https://github.com/typst/typst/issues/355 uses the `strike` function.
https://github.com/Leedehai/typst-physics/blob/443c963013b5cfea64818fa71990fefde9c93131/physica.typ#L750

Could this behaviour be documented in the manual? (I don't think there is a robust fix before https://github.com/typst/typst/issues/420 is resolved.)

### Workaround

```typst
#import "@preview/physica:0.9.3": hbar as _hbar

#show strike: set text(gray)
#let hbar = {
  show strike: set text(black)
  _hbar
}
```

**Comment by Leedehai** [comment]
Ah, that's a bit unfortunate. I'm on a travel and don't have my laptop with me now, though.. if you are convenient, could you make the edit to the markdown file and regenerate the PDF? Or, I'll modify when I'm back in a week or so.

**Comment by YDX-2147483647** [comment]
It is not an urgent issue, and that's fine. I can make the edit, but…

> make the edit to the _markdown_ file

do you mean `physica-manual.typ`?

Besides, it looks like that the PDF in the current repo predates typst 0.12.0, and now there are many subtle changes. It may take some time before I figure out if additional changes are required.

![](https://github.com/user-attachments/assets/8ed2dcc2-8276-495b-a7bd-6e74e9bf23a8)
