### ISSUE TITLE
D'Alambert Operator

### ISSUE THREAD

**Issue by marisbaier** [Leedehai/typst-physics#39]
Hi,

is the [d'Alambert operator](https://en.wikipedia.org/wiki/D%27Alembert_operator) available/needed? :)

**Comment by YDX-2147483647** [comment]
Maybe `square` is enough? (You can identify symbols at https://detypify.quarticcat.com)

```typst
$
  hat(square) A,
  square = diff^mu diff_mu
$
```

![](https://github.com/user-attachments/assets/32d0973c-c775-4bc3-b716-8e202dd31aeb)

https://tug.org/twg/mfg/mail-html/1993-08/msg00238.html
> The d'Alembertian…should be a) square, b) sitting on the base line and c) of about the same height as capital letters.
>
> It not easy to make all three requirements meet, b) is most often given up.
> The best LaTeX approximation was `$\Box$` from lasy, but it is not optimal.
