### ISSUE TITLE
Typst v0.12.0 changes

### ISSUE THREAD

**Issue by YDX-2147483647** [Leedehai/typst-physics#40]
As I said in https://github.com/Leedehai/typst-physics/issues/38#issuecomment-2513593430, I compare the results of `typst c physica-manual.typ` against https://github.com/typst/typst/releases/tag/v0.11.1 and https://github.com/typst/typst/releases/tag/v0.12.0.

Fortunately, most changes are negligible. The only two exceptions that I am not sure are the following. Are they also considered negligible?

### Order of the result of `BMEsymadd`

Typst v0.12.0 gives `ξ + a ξ`, but v0.11.1 gives `a ξ + ξ`.

```typst
$ BMEsymadd([xi,a xi]) $
```
https://github.com/Leedehai/typst-physics/blob/443c963013b5cfea64818fa71990fefde9c93131/physica-manual.typ#L1223

**Reason**: The items are sorted by sym ids. Typst v0.12.0 results in `("[ξ]", "sequence([a], [ξ])")`, while v0.11.0 results in `("[([a], [ξ])]", "[ξ]")`.
https://github.com/Leedehai/typst-physics/blob/443c963013b5cfea64818fa71990fefde9c93131/physica.typ#L126

### Spacing in matrices

Typst v0.12.0 generates narrower gaps than v0.11.1.

```typst
$ hmat(f; x,y) $
$ hmat(f;x,y;big:#true) $
```

![](https://github.com/user-attachments/assets/fe1b1f23-ce4d-43bc-abfe-5bee92391ee0)

https://github.com/Leedehai/typst-physics/blob/443c963013b5cfea64818fa71990fefde9c93131/physica-manual.typ#L349-L356

**Reason**: According to https://typst.app/docs/changelog/0.12.0/#math,

> Matrix and vector sizing is now more consistent across different cell contents.

**Comment by Leedehai** [comment]
Thank you for checking!

> Order of the result of BMEsymadd

Yes, the changed order is negligible. It doesn't change the semantics of the addition arithmetics, only the appearance of the result.

> Spacing in matrices

Well, okay it makes more sense to just accept that because it comes from the Typst change.

**Comment by YDX-2147483647** [comment]
Fine! Closing this issue…
