### ISSUE TITLE
CI for releases and manual generation?

### ISSUE THREAD

**Issue by YDX-2147483647** [Leedehai/typst-physics#8]
As mentioned in https://github.com/Leedehai/typst-physics/pull/7#issuecomment-1709150822, the PDF manual is not automatically generated now.

Do you want a CI for that? Say, when you click some buttom on GitHub or `git push --follow-tags`, a workflow will run and create a new release with the PDF manual.

Pros:
- Easier for maintenance and PR.
- Reduce the repo size in future. (because PDF will be stored in releases)

Cons:
- Setting up a CI from scratch is complicated.
- Being too dependent on GitHub.

More information:
- [GitHub Actions usage is free for public repositories.](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions)
- [yusancky/setup-typst](https://github.com/marketplace/actions/setup-typst) can download the typst binary from https://github.com/typst/typst/releases. (You can [look up Awesome Typst for alternatives](https://github.com/qjcg/awesome-typst?tab=readme-ov-file#cicd).)

If you like it but are busy, I can make a PR in one or two weeks.

**Comment by Leedehai** [comment]
Hi - I like this idea! I'd appreciate a PR. Thank you.
